###################error########################
*\/*
人気のハングリーヘブンでランチ☆

とにかく、肉感がすごい 
 Error: ;; Invalid input <*\ *\ *\ 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Invalid input <*\ *\ *\ 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
###########################################
###################error########################
*\/*
 
 Error: ;; Invalid input <*\ *\ *\ 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Invalid input <*\ *\ *\ 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
###########################################
###################error########################
くて美味しいで 
 'utf-8' codec can't decode bytes in position 464-465: invalid continuation byte
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 82, in parse
    knp_lines = self.subprocess.query(juman_str, pattern=r'^%s$'%(self.pattern))
  File "/usr/local/lib/python3.7/site-packages/pyknp/juman/process.py", line 70, in query
    line = self.stdouterr.readline().rstrip().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 464-465: invalid continuation byte
###########################################
###################error########################


アボカドバーガー 
 'utf-8' codec can't decode bytes in position 431-432: invalid continuation byte
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 82, in parse
    knp_lines = self.subprocess.query(juman_str, pattern=r'^%s$'%(self.pattern))
  File "/usr/local/lib/python3.7/site-packages/pyknp/juman/process.py", line 70, in query
    line = self.stdouterr.readline().rstrip().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 431-432: invalid continuation byte
###########################################
###################error########################

グリルグリルグリル 
 'utf-8' codec can't decode bytes in position 455-456: invalid continuation byte
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 82, in parse
    knp_lines = self.subprocess.query(juman_str, pattern=r'^%s$'%(self.pattern))
  File "/usr/local/lib/python3.7/site-packages/pyknp/juman/process.py", line 70, in query
    line = self.stdouterr.readline().rstrip().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 455-456: invalid continuation byte
###########################################
###################error########################
黒駅徒歩3分にある夜は焼肉屋昼はハンバーガー屋 
 Error: ;; Invalid input <+ + + 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Invalid input <+ + + 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
###########################################
