###################error########################
妻とのスイーツ食べ歩き第二弾は,行きたいチェックしていたモンサンクレール｡
平日の昼前でも待ちが出るとは,凄い人気ですね｡
休日だと店外まで行列ができそうですね(^_^;

注文したのは,人気のモンブランとアヴニール｡

モンブランは,洋風のモンブランとしては今までで最上位に美味しい一品｡栗の風味は強くないですが,仄かな苦味とクリームとの相性は素晴らしい｡皆さんが絶賛するのも頷けます｡

アヴニールは,完全に見た目で選びました｡
ミントはあまり得意ではないですが,ココナッツとライムは好きなので大丈夫かと思い選んだら,予想以上の当たりです｡
ミントはもちろん香りますが,フロマージュブランの滑らかなムースとライムの酸味が良い具合に混ざりあい,口当たりは非常に爽やかです｡
ミントが使われているお菓子で,1番美味しい一品でした｡ 
 Error: ;; Too many mrph ( ...)!
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Too many mrph ( ...)!
###########################################
###################error########################
タルトペッシュ950円　+　アールグレイ500円
昼メシ前に通りがかったら空いていた 
 Error: ;; Invalid input <+ + + 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Invalid input <+ + + 未定義語 15 その他 1 * 0 * 0 "品詞推定:名詞"
###########################################
###################error########################
スイーツ王国自由が丘の中でも聖地と呼ばれるお店だけあって、どれも美味しそうで選べない^^;
フルーツがいろいろ載ったチョコケーキを買って帰りました 
 list index out of range
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 43, in __init__
    self._setPAS(juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 79, in _setPAS
    tag.pas = Pas(tag.tag_id, self)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 87, in __init__
    self.__set_args(tag_predicate.features.get("項構造"), CaseInfoFormat.PASv41)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 186, in __set_args
    for items in self.__parse_case_analysis_items(analysis_result, case_info_format):
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 181, in __parse_case_analysis_items
    yield self.__parse_case_info_format(items, case_info_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 145, in __parse_case_info_format
    eid = int(items[3])
IndexError: list index out of range
###########################################
###################error########################

２種類のモンブランをイートインすることをお店の方に伝えると、お持ち帰り用にフォンダンショコラ、日曜日限定のタルト、タルトシトロンを強く勧められ、ついつい言われた通りにオーダーしてしまいました(^^;;
オーダーを済ませて着席すると、お昼時のためか、日曜日なのに僕以外にイートインのお客様はおらず、またしても貸切状態です 
 list index out of range
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 43, in __init__
    self._setPAS(juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 79, in _setPAS
    tag.pas = Pas(tag.tag_id, self)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 87, in __init__
    self.__set_args(tag_predicate.features.get("項構造"), CaseInfoFormat.PASv41)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 186, in __set_args
    for items in self.__parse_case_analysis_items(analysis_result, case_info_format):
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 181, in __parse_case_analysis_items
    yield self.__parse_case_info_format(items, case_info_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 145, in __parse_case_info_format
    eid = int(items[3])
IndexError: list index out of range
###########################################
###################error########################
開店３０分前に到着⸜⸝⋆︎*台風の影響か、一番に構えることが出来ました 
 Error: ;; Invalid input <* * * 特殊 1 記号 5 * 0 * 0 NIL
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Invalid input <* * * 特殊 1 記号 5 * 0 * 0 NIL
###########################################
###################error########################
人気店であるのは間違いありません(;^_^A
テーブルについてから、ダージリンをオーダー 
 list index out of range
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 43, in __init__
    self._setPAS(juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 79, in _setPAS
    tag.pas = Pas(tag.tag_id, self)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 87, in __init__
    self.__set_args(tag_predicate.features.get("項構造"), CaseInfoFormat.PASv41)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 186, in __set_args
    for items in self.__parse_case_analysis_items(analysis_result, case_info_format):
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 181, in __parse_case_analysis_items
    yield self.__parse_case_info_format(items, case_info_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 145, in __parse_case_info_format
    eid = int(items[3])
IndexError: list index out of range
###########################################
###################error########################
モンサンクレール@自由が丘

スイーツタウン自由が丘でも、此方の人気はダントツですね

引っ切り無しに、お客様が買ったり注文したり…

地元の人達が少ないのも、この店らしいかも⁉︎…(^^;;

バースデーケーキを昨日の帰りにオーダーしましたが、食べる前に子供達が倒してママは泣きが入り… 
 list index out of range
Traceback (most recent call last):
  File "/Users/itsp/Docker/DockerfileForWSD/workspace/NLPLibrary/nlplib_pyknp2.py", line 308, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 43, in __init__
    self._setPAS(juman_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/blist.py", line 79, in _setPAS
    tag.pas = Pas(tag.tag_id, self)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 87, in __init__
    self.__set_args(tag_predicate.features.get("項構造"), CaseInfoFormat.PASv41)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 186, in __set_args
    for items in self.__parse_case_analysis_items(analysis_result, case_info_format):
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 181, in __parse_case_analysis_items
    yield self.__parse_case_info_format(items, case_info_format)
  File "/usr/local/lib/python3.7/site-packages/pyknp/knp/pas.py", line 145, in __parse_case_info_format
    eid = int(items[3])
IndexError: list index out of range
###########################################
